#!/usr/bin/env node

const shell = require("shelljs");

exports.command = "publish-packages";
exports.describe =
    "publishes all packages recently built by assemble-packages and deletes them aftewards";
exports.builder = function (yargs) {
  return yargs.option({
    source: {
      type: "string", default: "dist/publish",
      description: `source directory for the packages to be published. ${
          ""}Each package in this directory will be destroyed after successful publish.`
    }
  });
};
exports.handler = function (argv) {
  const packages = shell.find("dist/publish/**/package.json")
      .filter(packagePath => !packagePath.includes("node_modules"))
      .map(packagePath => packagePath.match(/(.*)\/package.json/)[1]);

  for (var package of packages) {
    var publishResult = shell.exec(`npm publish ${package}`);
    if (!publishResult.code) {
      shell.rm("-rf", package);
    } else {
      console.log("Published with code", publishResult.code, publishResult);
    }
  }
}
